name: CI

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      version:
        type: string
        default: ""
      latest:
        type: string
        default: "true"
      build-args:
        type: string
        default: ""
      s6:
        type: boolean
        default: false

env:
  S6_OVERLAY_VERSION: "3.1.6.2"

jobs:
  build-for-linux:
    name: Build - ${{ matrix.job.name }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: "amd64",   docker_platform: "linux/amd64",  s6_platform: "x86_64" }
          - { name: "arm64v8", docker_platform: "linux/arm64",  s6_platform: "aarch64" }
          - { name: "armv7",   docker_platform: "linux/arm/v7", s6_platform: "armhf" }
          - { name: "i386",    docker_platform: "linux/386",    s6_platform: "i686" }
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: docker_buildx

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.name }}
            ghcr.io/${{ github.repository_owner }}/${{ inputs.name }}
          tags: |
            type=raw,value={{date 'YYYY-MM-DD' tz='Asia/Shanghai'}},enable=${{ inputs.version == '' }}
            type=raw,value=${{ inputs.version }},enable=${{ inputs.version != '' }}
          # avoid overwriting the latest tag because metadata-action does not add a suffix to it
          flavor: |
            latest=false
            suffix=-${{ matrix.job.name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        if: inputs.s6 == false
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.name }}
          platforms: ${{ matrix.job.docker_platform }}
          build-args: ${{ inputs.build-args }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha

      - name: Build and push
        if: inputs.s6 != false
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.name }}
          platforms: ${{ matrix.job.docker_platform }}
          build-args: |
            S6_ARCH=${{ matrix.job.s6_platform }}
            S6_OVERLAY_VERSION=${{ env.S6_OVERLAY_VERSION }}
            ${{ inputs.build-args }}
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha

  merge-multi-architecture:
    name: Merge multi-architecture image
    needs:
     - build-for-linux
    runs-on: ubuntu-latest
    steps:
      - name: Docker meta
        uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ inputs.name }}
            ghcr.io/${{ github.repository_owner }}/${{ inputs.name }}
          tags: |
            type=raw,value={{date 'YYYY-MM-DD' tz='Asia/Shanghai'}},enable=${{ inputs.version == '' }}
            type=raw,value=${{ inputs.version }},enable=${{ inputs.version != '' }}
            type=raw,value=latest,enable=${{ inputs.latest == 'true' }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create manifest list and push
        uses: int128/docker-manifest-create-action@v1
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          suffixes: |
            -amd64
            -arm64v8
            -armv7
            -i386
