name: Meta Dashboard CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/metad.yml
      - metad/**

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    with:
      name: metad
      version: ${{ vars.METAD_VERSION }}
      latest: ${{ vars.METAD_LATEST }}
      build-args: |
        METAD_VERSION=${{ vars.METAD_VERSION }}
        NODE_IMAGE=${{ vars.METAD_NODE_IMAGE }}
        NGINX_IMAGE=${{ vars.METAD_NGINX_IMAGE }}
    secrets: inherit