name: Nginx CI

on:
  workflow_dispatch:

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    with:
      name: nginx
      s6: true
      build-args: |
        NGINX_IMAGE=${{ vars.NGINX_IMAGE }}
    secrets: inherit