name: Nginx CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/nginx.yml
      - nginx/**

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    with:
      name: nginx
      version: ${{ vars.NGINX_VERSION }}
      latest: ${{ vars.NGINX_LATEST }}
      build-args: |
        NGINX_IMAGE=nginx:${{ vars.NGINX_VERSION }}-alpine
    secrets: inherit