name: Sub-Store CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/sub-store.yml
      - sub-store/**

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    with:
      name: sub-store
    secrets: inherit