name: Yacd-Meta CI

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/yacd-meta.yml
      - yacd-meta/**

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yml
    with:
      name: yacd-meta
      version: ${{ vars.YACD_META_VERSION }}
      latest: ${{ vars.YACD_META_LATEST }}
      build-args: |
        YACD_META_VERSION=${{ vars.YACD_META_VERSION }}
        NODE_IMAGE=${{ vars.YACD_META_NODE_IMAGE }}
        NGINX_IMAGE=${{ vars.YACD_META_NGINX_IMAGE }}
    secrets: inherit